# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required:
version: 2


sphinx:
  builder: html
  configuration: doc/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  version: 3.7
  install:
    - requirements:  doc/source/requirements.txt



