# autogenerated file. do not change
import pathlib
DIR_TESTDATA = pathlib.Path(__file__).parent
speclib = DIR_TESTDATA / 'SpecLib_BerlinUrbanGradient.sli'
Landsat8_West_tif = DIR_TESTDATA / 'Landsat8.West.tif'
Landsat8_East_tif = DIR_TESTDATA / 'Landsat8.East.tif'
Sentinel2_West_tif = DIR_TESTDATA / 'Sentinel2.West.tif'
Sentinel2_East_tif = DIR_TESTDATA / 'Sentinel2.East.tif'
RapidEye_tif = DIR_TESTDATA / 'RapidEye.tif'